apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['tail', '-f', '/dev/null']
      env:
        - name: A
          valueFrom:
            secretKeyRef:
              name: secret
              key: a
        - name: B
          valueFrom:
            secretKeyRef:
              name: secret
              key: b
        - name: CONFIG_YAML
          valueFrom:
            secretKeyRef:
              name: secret
              key: config.yaml
        - name: CONFIG_JSON
          valueFrom:
            secretKeyRef:
              name: secret
              key: config.json
