apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      id: disk
  storageClassName: ebs

