apiVersion: v1
kind: Pod
metadata:
  name: disk-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['tail', '-f', '/dev/null']
      volumeMounts:
        - mountPath: /disk
          name: disk
  volumes:
    - name: disk
      persistentVolumeClaim:
        claimName: disk-claim
