apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-volume
  labels:
    id: disk
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0e99eabe1f8589076
    fsType: ext4
  storageClassName: ebs

