apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Chart.Name .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-%s" .Chart.Name .Release.Name }}
  ports:
    - port: 6379

