apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Chart.Name .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-%s" .Chart.Name .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Chart.Name .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
