apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  containers:
    - command: ['tail', '-f', '/dev/null']
      name: ubuntu
      image: ubuntu
      volumeMounts:
        - mountPath: /data
          name: data
  initContainers:
    - args: ['clone', 'https://github.com/larkintuckerllc/lab-notebook.git']
      name: git
      image: alpine/git
      volumeMounts:
        - mountPath: /git
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}
