apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app | quote }}
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.app | quote }}
  ports:
    - port: 80
