apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::143287522423:role/aws-eks-APIRole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 143287522423.dkr.ecr.us-east-1.amazonaws.com/aws-eks-api:latest
          ports:
            - containerPort: 80
          env:
            - name: REGION
              value: "us-east-1"
      serviceAccountName: api
---
apiVersion: v1
kind: Service
metadata:
  name: api-load-balancer-ssl
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:143287522423:certificate/e4d16508-aeee-4df5-bf7b-7595bf2280af
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
  type: LoadBalancer


