apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: 143287522423.dkr.ecr.us-east-1.amazonaws.com/aws-eks-hello-world:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-load-balancer-ssl
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:143287522423:certificate/e4d16508-aeee-4df5-bf7b-7595bf2280af
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
  type: LoadBalancer

