apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-ssl
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:143287522423:certificate/e4d16508-aeee-4df5-bf7b-7595bf2280af
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
  type: LoadBalancer

