apiVersion: v1
kind: Pod
metadata:
  name: file-system
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['tail', '-f', '/dev/null']
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: example
