apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          env:
            - name: REDIS_URL
              value: {{ printf "redis://redis-%s" .Release.Name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /probe
              port: http

