apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    release: b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        release: b
    spec:
      containers:
        - name: app
          image: localhost:32000/api
          ports:
            - containerPort: 80

