apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app | quote }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.app | quote }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: localhost:32000/api
          ports:
            - containerPort: 80

