apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 50M
---
apiVersion: v1
kind: Pod
metadata:
  name: persistent-volume
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['tail', '-f', '/dev/null']
      volumeMounts:
        - mountPath: /disk
          name: disk
  volumes:
    - name: disk
      persistentVolumeClaim:
        claimName: disk
